const fs = require('fs');
const path = require('path');

const dbPath = path.resolve(__dirname, '../data/app_database.json');
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

const cleanUrl = 'https://playabledownloads.com/show.php?l=0&u=2559473&id=1916896&tracking_id={userId}&subid={trackingToken}';

const extraOffers = [
  {
    id: 9,
    title: 'HD Stream: CyberShield VPN Ultimate',
    description: 'Watch a 30-second security briefing on military-grade encryption for public WiFi safety.',
    category: 'VIDEO_AD',
    reward_coins: 180,
    estimated_minutes: 1,
    requirements: 'Watch full 30 seconds without skipping.',
    provider_id: 'cpagrip',
    external_offer_id: 'vid_105',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 8,
    active: true,
    created_at: new Date().toISOString(),
    video_duration_sec: 30,
    sponsor_brand: 'CyberShield Security',
    banner_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 10,
    title: 'Quick Video: TurboGamer Wireless Headset',
    description: 'Experience ultra-low latency spatial gaming audio in this dynamic 15-second sponsor spotlight.',
    category: 'VIDEO_AD',
    reward_coins: 100,
    estimated_minutes: 1,
    requirements: 'Watch 15 seconds verified playback.',
    provider_id: 'cpagrip',
    external_offer_id: 'vid_106',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 10,
    active: true,
    created_at: new Date().toISOString(),
    video_duration_sec: 15,
    sponsor_brand: 'TurboGamer Gear',
    banner_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 11,
    title: 'Sponsor Showcase: NeoBank Zero Fee Card',
    description: 'Discover borderless multi-currency debit accounts with zero foreign transaction fees.',
    category: 'VIDEO_AD',
    reward_coins: 160,
    estimated_minutes: 1,
    requirements: 'Watch 30 seconds verified playback.',
    provider_id: 'cpagrip',
    external_offer_id: 'vid_107',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 6,
    active: true,
    created_at: new Date().toISOString(),
    video_duration_sec: 30,
    sponsor_brand: 'NeoBank Global',
    banner_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 12,
    title: 'Video Reel: PixelStudio AI Photo Editor',
    description: 'See 1-click background removal and generative image expansion in action.',
    category: 'VIDEO_AD',
    reward_coins: 140,
    estimated_minutes: 1,
    requirements: 'Watch 20 seconds verified playback.',
    provider_id: 'cpagrip',
    external_offer_id: 'vid_108',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 8,
    active: true,
    created_at: new Date().toISOString(),
    video_duration_sec: 20,
    sponsor_brand: 'PixelStudio Pro',
    banner_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 13,
    title: 'Fast App Install: TradePro Stock & Crypto Trading',
    description: 'Download TradePro, register free account and check live market prices to unlock reward.',
    category: 'APP_INSTALL',
    reward_coins: 950,
    estimated_minutes: 3,
    requirements: 'Install app, open and complete free registration.',
    provider_id: 'cpagrip',
    external_offer_id: 'app_202',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 2,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'TradePro Markets',
    banner_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 14,
    title: 'Casual Game: Bubble Shooter Legend Adventure',
    description: 'Install and reach stage 5 in this relaxing puzzle game.',
    category: 'APP_INSTALL',
    reward_coins: 500,
    estimated_minutes: 3,
    requirements: 'Install and complete stage 5.',
    provider_id: 'cpagrip',
    external_offer_id: 'app_203',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 3,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'JoyPlay Games',
    banner_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 15,
    title: 'Utility App: BatterySaver Pro & Memory Cleaner',
    description: 'Install utility app and run 1-click device optimization scan.',
    category: 'APP_INSTALL',
    reward_coins: 420,
    estimated_minutes: 2,
    requirements: 'Install and open app once.',
    provider_id: 'cpagrip',
    external_offer_id: 'app_204',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 4,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'UtilitySoft',
    banner_url: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 16,
    title: 'Fast App: FitLife Daily Workout & Calorie Tracker',
    description: 'Install FitLife fitness coach app and set your weekly fitness goal.',
    category: 'APP_INSTALL',
    reward_coins: 680,
    estimated_minutes: 4,
    requirements: 'Install and create your personalized workout profile.',
    provider_id: 'cpagrip',
    external_offer_id: 'app_205',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 3,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'FitLife Studio',
    banner_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 17,
    title: 'Quick Poll: Daily Tech & Smartphone Habits',
    description: 'Answer 4 quick multiple-choice questions on 5G network speeds and daily screen time.',
    category: 'SURVEY',
    reward_coins: 350,
    estimated_minutes: 2,
    requirements: 'Answer all 4 questions attentively.',
    provider_id: 'cpagrip',
    external_offer_id: 'surv_302',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 5,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'TechInsight Labs',
    banner_url: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 18,
    title: 'Entertainment Survey: OTT Streaming & Cinema Preferences',
    description: 'Vote on your favorite genres, movie release platforms, and subscription services.',
    category: 'SURVEY',
    reward_coins: 480,
    estimated_minutes: 3,
    requirements: 'Complete all 5 questions.',
    provider_id: 'cpagrip',
    external_offer_id: 'surv_303',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 4,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'MediaMetrics Global',
    banner_url: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 19,
    title: 'Finance Opinion: Digital Payments & UPI 2026',
    description: 'Share your feedback on contactless tap-to-pay, QR payments and cashback offers.',
    category: 'SURVEY',
    reward_coins: 550,
    estimated_minutes: 3,
    requirements: 'Complete the short 6-question questionnaire.',
    provider_id: 'cpagrip',
    external_offer_id: 'surv_304',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 3,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'FinPoll Analytics',
    banner_url: 'https://images.unsplash.com/photo-1556742049-0a67e557224d?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 20,
    title: 'Free Registration: PrimeRewards Club VIP Trial',
    description: 'Create a free membership account to browse discount vouchers and cashback deals.',
    category: 'SIGNUP',
    reward_coins: 500,
    estimated_minutes: 2,
    requirements: 'Register free account with valid email.',
    provider_id: 'cpagrip',
    external_offer_id: 'sgn_402',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 3,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'PrimeRewards Network',
    banner_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 21,
    title: 'Email Signup: TechTrends Weekly AI Brief',
    description: 'Subscribe to the premier AI newsletter to receive curated Monday morning summaries.',
    category: 'SIGNUP',
    reward_coins: 380,
    estimated_minutes: 1,
    requirements: 'Submit your email and confirm subscription.',
    provider_id: 'cpagrip',
    external_offer_id: 'sgn_403',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 5,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'TechTrends Media',
    banner_url: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 22,
    title: 'Student Free Account: LearnCode Python Academy',
    description: 'Sign up for free beginner Python interactive tutorial track.',
    category: 'SIGNUP',
    reward_coins: 620,
    estimated_minutes: 3,
    requirements: 'Complete free learner account signup.',
    provider_id: 'cpagrip',
    external_offer_id: 'sgn_404',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 2,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'LearnCode Online',
    banner_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 23,
    title: 'Cricket Trivia: World Cup Champions Challenge',
    description: 'Answer 5 quick cricket trivia questions to demonstrate your sports knowledge.',
    category: 'CPA_OFFER',
    reward_coins: 600,
    estimated_minutes: 2,
    requirements: 'Pass trivia with at least 4 out of 5 correct.',
    provider_id: 'cpagrip',
    external_offer_id: 'cpa_502',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 3,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'SportTrek Media',
    banner_url: 'https://images.unsplash.com/photo-1531415074868-036b1c57e329?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: 24,
    title: 'Scratch & Win: Lucky Gold Ticket Giveaway',
    description: 'Scratch digital golden ticket to reveal instant sponsor coupon code and bonus coins.',
    category: 'CPA_OFFER',
    reward_coins: 800,
    estimated_minutes: 2,
    requirements: 'Complete scratch card verification step.',
    provider_id: 'cpagrip',
    external_offer_id: 'cpa_503',
    tracking_url_template: cleanUrl,
    target_countries: 'ALL',
    daily_cap: 2,
    active: true,
    created_at: new Date().toISOString(),
    sponsor_brand: 'LuckySpin Global',
    banner_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80'
  }
];

// Clean existing offers
db.offers = db.offers.map(o => ({
  ...o,
  active: true,
  tracking_url_template: cleanUrl
}));

// Add extra offers
extraOffers.forEach(eo => {
  if (!db.offers.some(o => o.id === eo.id)) {
    db.offers.push(eo);
  }
});

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
console.log('Successfully seeded database! Total offers:', db.offers.length);
